include ${KITTY_OS}.conf
# Colors
background #062625
foreground #d0b892
selection_foreground #d0b892
selection_background #8cde94
cursor #d0b892

# Tabs
tab_bar_edge top
active_tab_background   #1c4a49
active_tab_foreground   #d0b892

inactive_tab_background #0b3335
inactive_tab_foreground #7a8478

inactive_tab_font_style normal
tab_bar_background      #062625

# ANSI palette
color0  #0b3335
color1  #F92672
color2  #8cde94
color3  #E6DB74
color4  #66D9EF
color5  #AE81FF
color6  #A1EFE4
color7  #ffffff
color8  #7a8478
color9  #F92672
color10 #8cde94
color11 #E6DB74
color12 #66D9EF
color13 #F92672
color14 #83c092
color15 #ffffff

# Cursor
cursor_shape block
shell_integration no-cursor

# Font
font_family      Liga SFMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_features LigaSFMonoNerdFont-Regular +calt +liga +dlig +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08

map ctrl+c copy_or_interrupt

hide_window_decorations yes
