return {
	main_mod = "SUPER",
	terminal = "ghostty",
	browser = "zen-browser",
	personal_browser = 'zen-browser -P "Personal"',
	work_browser = 'zen-browser -P "Work"',
	launcher = "hyprlauncher",
	file_manager = "thunar",
	bluetooth_manager = "blueman-manager",
	lock = "hyprlock",
	music = "spotify",
	sunset_warmer = "hyprctl hyprsunset temperature -500",
	sunset_cooler = "hyprctl hyprsunset temperature +500",
	vpn_connect = "protonvpn connect --country AT",
	vpn_disconnect = "protonvpn disconnect",
	screenshot_region = "hyprshot -m region",
	screenshot_output = "hyprshot -m output",
	ime_toggle = "fcitx5-remote -t",
	autostart = {
		"waybar",
		"hyprpaper",
		"hypridle",
		"hyprsunset",
		"fcitx5 -d",
		"systemctl --user start hyprpolkitagent",
		"protonvpn-app",
	},
}
